"""added crontab table

Revision ID: d059fa14cb14
Revises: 10680f8f7880
Create Date: 2022-03-08 10:01:59.511354

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d059fa14cb14"
down_revision = "10680f8f7880"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celery_crontab_schedule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("minute", sa.String(length=240), nullable=True),
        sa.Column("hour", sa.String(length=96), nullable=True),
        sa.Column("day_of_week", sa.String(length=64), nullable=True),
        sa.Column("day_of_month", sa.String(length=124), nullable=True),
        sa.Column("month_of_year", sa.String(length=64), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="scheduler",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("celery_crontab_schedule", schema="scheduler")
    # ### end Alembic commands ###
