"""added periodic task tables

Revision ID: 0b77b4703c76
Revises: bc68e9cf43a6
Create Date: 2022-03-08 10:08:09.324602

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0b77b4703c76"
down_revision = "bc68e9cf43a6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celery_periodic_task",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("task", sa.String(length=255), nullable=True),
        sa.Column("interval_id", sa.Integer(), nullable=True),
        sa.Column("crontab_id", sa.Integer(), nullable=True),
        sa.Column("solar_id", sa.Integer(), nullable=True),
        sa.Column("args", sa.Text(), nullable=True),
        sa.Column("kwargs", sa.Text(), nullable=True),
        sa.Column("queue", sa.String(length=255), nullable=True),
        sa.Column("exchange", sa.String(length=255), nullable=True),
        sa.Column("routing_key", sa.String(length=255), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("expires", sa.DateTime(timezone=True), nullable=True),
        sa.Column("one_off", sa.Boolean(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_run_count", sa.Integer(), nullable=False),
        sa.Column("date_changed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="scheduler",
    )
    op.create_table(
        "celery_periodic_task_changed",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_update", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="scheduler",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("celery_periodic_task_changed", schema="scheduler")
    op.drop_table("celery_periodic_task", schema="scheduler")
    # ### end Alembic commands ###
