"""added interval schedule table

Revision ID: 10680f8f7880
Revises:
Create Date: 2022-03-08 00:20:31.874083

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10680f8f7880"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "celery_interval_schedule",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("every", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=24), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="scheduler",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("celery_interval_schedule", schema="scheduler")
    # ### end Alembic commands ###
